name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.2'
          cache: yarn

      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true

      - run: yarn install --frozen-lockfile
      - run: yarn build
      # - run: yarn test
      # - run: yarn test:smoke
